---
title: "Osa Conservation: Impact map"
author:
  - Chris Beirne
site: bookdown::test-bookdown
output: bookdown::gitbook
documentclass: book
biblio-style: apalike
link-citations: yes
editor_options: 
  chunk_output_type: console
---

# Impact map

```{r c01, echo=F, message=F, include=F}
knitr::opts_chunk$set(echo = FALSE, message=F, warning=F)

#library(rgdal) 
library(move) 
library(dplyr)
library(leaflet)
library(units)
library(sf)
library(viridis)
library(kableExtra)
library(lubridate)
library(plotly)
## Load packages for google drive ----
library(googledrive)
library(purrr)
library(readxl)
library(geosphere)
library(foreach)
library(maptools)
library(leaflet.opacity)
library(leaflet.extras)

options(googledrive_quiet = TRUE)

# For when the trapping effort file is sorted
# googledrive::drive_auth(path = Sys.getenv("GOOGLE_AUTHENTICATION_CREDENTIALS"))
# 
# ## Find Google Drive folder 'Centre Circle Data & Info'
# data_folder <- drive_ls(path = "08 Databases + Analysis")
# data_path <- "data" 
# dir.create(data_path) 
# drive_download(as_id("14hLi94W4WbDn6jdXahJMnxllOgLpZh-PpIBOWqt9jlc"),
#                path="data/2_vulture_trap_deployments.xlsx")
#capture_dat <- read_excel("data/2_vulture_trap_deployments.xlsx")


# 
# # Import passcodes
# MOVE_PASS <- Sys.getenv("MOVEBANK_PASSWORD")
# MOVE_USE  <- Sys.getenv("MOVEBANK_USERNAME")
# 
# loginStored <- movebankLogin(username=MOVE_USE, 
#                              password=MOVE_PASS)
# 
# # Get animals
# # Vultures
# animals <-getMovebankAnimals(study=1573471517,login=loginStored)
# # Ocelot
# tmp <-getMovebankAnimals(study=2526574641,login=loginStored)
# # Tapir
# tmp2 <- getMovebankAnimals(study=1954804459,login=loginStored)
# animals <- rbind(animals, tmp,tmp2)
# 
# # For some reason they are duplicated
# animals[duplicated(animals)==F,]
# # They vary by the field "sensor_type_id"
# animals <- animals[animals$sensor_type_id==653 & is.na(animals$sensor_type_id)==F,]
# 
# # Clean up the name
# animals$animalName <- paste0(sub('\\_.*', '', animals$animalName), "_", sub('\\ .*', '', animals$taxon_canonical_name))
# animals$name <- sub('\\_.*', '', animals$animalName)
# 
# # Sort date objects
# animals$timestamp_start <- ymd_hms(animals$timestamp_start)
# animals$timestamp_end <- ymd_hms(animals$timestamp_end)
# 
# # Get last 2 weeks
# t <- now("America/Costa_Rica")
# start_t <- t-as.difftime(14,units='days')
# start_tapir <- t-as.difftime(48,units='days')
# 
# # Vultures
# mov_dat <- getMovebankData(study=1573471517, login=loginStored,  removeDuplicatedTimestamps=TRUE,
#                        timestamp_start=start_t)
# #OCelot
# tmp <- getMovebankData(study=2526574641, login=loginStored,  removeDuplicatedTimestamps=TRUE,
#                        timestamp_start=start_t)
# 
# #Tapir
# tmp2 <- getMovebankData(study=1954804459, login=loginStored,  removeDuplicatedTimestamps=TRUE,
#                        timestamp_start=start_tapir)
# 
# # Remove the obvious outlier
# tmp2 <- tmp2[tmp2$location_lat>8,]
# 
# mov_dat <- moveStack(mov_dat, tmp, tmp2)
# 
# 
# 
# #Add the names
# mov_dat$name <- trackId(mov_dat)
# 
# 
# # Convert timezone
# mov_dat$timestamp <- with_tz(timestamps(mov_dat), tz="America/Costa_Rica")
# 
# # all data
# #dat <- getMovebankData(study=1573471517, login=loginStored,  removeDuplicatedTimestamps=TRUE)
# 
# # Convery move stack to dataframe
# dat <- as.data.frame(mov_dat)
# 
# # Convert dat to costa rica time
# dat$timestamp <- with_tz(dat$timestamp, tzone = "America/Costa_Rica")
# 
# # Add the location data
# dat <- left_join(dat, animals[, c("tag_id", "animalName")])
# # Sort the names out
# 
# dat$animalName <- sub('\\_.*', '', dat$animalName)
# # Add in the taxonomic group
# dat$animalName <- paste0(dat$animalName, "_", sub('\\ .*', '', dat$taxon_canonical_name))
# 
# # # Setup the leaflet icon
# # leafIcons <- icons(
# #   iconUrl = "https://raw.githubusercontent.com/ChrisBeirne/Osa-Conservation-Movement-Ecology-Daily-Report/main/icons/vul_small1.png",
# #   iconWidth = 38, iconHeight = 40,
# #   iconAnchorX = 22, iconAnchorY = 39,
# #   shadowUrl = "https://raw.githubusercontent.com/ChrisBeirne/Osa-Conservation-Movement-Ecology-Daily-Report/main/icons/vul_small_shadow.png",
# #   shadowWidth = 38, shadowHeight = 30,
# #   shadowAnchorX = 4, shadowAnchorY = 39
# # )
# # #?iconList()
# 
# papa <- makeIcon(
#   iconUrl = "https://raw.githubusercontent.com/ChrisBeirne/Osa-Conservation-Movement-Ecology-Daily-Report/main/icons/king_small.png",
#   iconWidth = 38, iconHeight = 40,
#   iconAnchorX = 22, iconAnchorY = 39,
#   shadowUrl = "https://raw.githubusercontent.com/ChrisBeirne/Osa-Conservation-Movement-Ecology-Daily-Report/main/icons/vul_small_shadow.png",
#   shadowWidth = 38, shadowHeight = 30,
#   shadowAnchorX = 4, shadowAnchorY = 39)
# 
# aura <- makeIcon(
#   iconUrl = "https://raw.githubusercontent.com/ChrisBeirne/Osa-Conservation-Movement-Ecology-Daily-Report/main/icons/turk_small.png",
#   iconWidth = 38, iconHeight = 40,
#   iconAnchorX = 22, iconAnchorY = 39,
#   shadowUrl = "https://raw.githubusercontent.com/ChrisBeirne/Osa-Conservation-Movement-Ecology-Daily-Report/main/icons/vul_small_shadow.png",
#   shadowWidth = 38, shadowHeight = 30,
#   shadowAnchorX = 4, shadowAnchorY = 39)
# 
# mela <- makeIcon(
#   iconUrl = "https://raw.githubusercontent.com/ChrisBeirne/Osa-Conservation-Movement-Ecology-Daily-Report/main/icons/yhv_small.png",
#   iconWidth = 38, iconHeight = 40,
#   iconAnchorX = 22, iconAnchorY = 39,
#   shadowUrl = "https://raw.githubusercontent.com/ChrisBeirne/Osa-Conservation-Movement-Ecology-Daily-Report/main/icons/vul_small_shadow.png",
#   shadowWidth = 38, shadowHeight = 30,
#   shadowAnchorX = 4, shadowAnchorY = 39)
# 
# pardalis <- makeIcon(
#   iconUrl = "https://raw.githubusercontent.com/ChrisBeirne/Osa-Conservation-Movement-Ecology-Daily-Report/main/icons/ocelot.png",
#   iconWidth = 38, iconHeight = 40,
#   iconAnchorX = 22, iconAnchorY = 39)
# 
# bairdii <- makeIcon(
#   iconUrl = "https://raw.githubusercontent.com/ChrisBeirne/Osa-Conservation-Movement-Ecology-Daily-Report/main/icons/tapir.png",
#   iconWidth = 38, iconHeight = 40,
#   iconAnchorX = 22, iconAnchorY = 39)
# 
# iconSet <- iconList(aura= aura,
#                     papa =papa,
#                     melambrotus = mela,
#                     pardalis = pardalis,
#                     bairdii = bairdii)
# 
# dat$icon <- sub(".*? ", "", dat$taxon_canonical_name)
# 
# 
# # Add costa rica survey locations
# cr_locs<- data.frame(location_code=c("AIRS02", "CERR02","LOMAS01"), 	
#            latitude=c(8.402595,	8.416142,8.758321)	,
#            longitude=c( -83.35852,	-83.31793,	-83.29787) )



##########################
# import spatial data

cams_1 <- st_read("data/Cam Trap Grid 2018.shp")
cams_2 <- st_read("data/Mega_Survey_set_-_Final_March_2020 waypoints.shp")
kids <- st_read("data/kids club partners.shp")
oc <- st_read("data/oc_propertiers_clean.shp")
oc <- st_zm(oc)
rest <- st_read("data/restoration partners.shp")
road <- st_read("data/Road Study 2021.shp")
road <- road[st_coordinates(road)[,1] < (-80),]
```




```{r}
m <- leaflet() %>%
  # Add a satellite image layer
  addProviderTiles(providers$Stamen.TonerLite, group="Simple") %>%
  addProviderTiles(providers$Esri.WorldImagery, group="Satellite") %>%
  addProviderTiles(providers$OpenStreetMap.Mapnik, group="OS") #%>%     

 m <- m %>%
    addPolygons(data = oc, color = "pink", group = "property", weight=3,fillOpacity=1,stroke=F, popup="property") %>%
    addCircleMarkers(data = cams_1, color = "blue", group = "camera trap", weight=1,opacity=1, radius=1, popup="cameratraps") %>%
    addCircleMarkers(data = cams_2, color = "blue", group = "camera trap", weight=1,opacity=1, radius=1, popup="cameratraps") %>%
    addCircleMarkers(data = kids, color = "yellow", group = "kids club", weight=1,opacity=1, radius=1, popup="kids clubs")   %>%
    addCircleMarkers(data = road, color = "purple", group = "road survey", weight=1,opacity=1, radius=1, popup="road survey")   %>%
    addCircleMarkers(data = rest, color = "orange", group = "restoration", weight=1,opacity=1, radius=1, popup="restoration")    %>% 
     addLayersControl(
        baseGroups = c("OS", "Simple", "Satellite"),
        overlayGroups = c("property","restoration","camera trap","kids club", "road survey", "restoration"),
        options = layersControlOptions(collapsed = FALSE)
      ) %>%
  addFullscreenControl() %>% 
   addLegend(colors=c("pink", "blue", "yellow", "purple", "orange"), labels=c("property","camera trap","kids club", "road survey", "restoration"), opacity=1)
 
 
m
```

